#!/bin/bash

# Función para verificar si un paquete está instalado
check_package() {
  dpkg -l $1 &> /dev/null
  return $?
}

# Función para verificar si un directorio existe
check_directory() {
  [ -d "$1" ]
  return $?
}

# Verificar si git está instalado
if ! check_package git; then
  apt update
  apt install -y git
fi

# Verificar si zip está instalado
if ! check_package zip; then
  apt update
  apt install -y zip
fi

# Verificar si unzip está instalado
if ! check_package unzip; then
  apt update
  apt install -y unzip
fi

# Verificar si curl está instalado
if ! check_package curl; then
  apt update
  apt install -y curl
fi

# Verificar si Node.js está instalado
if ! check_package nodejs; then
  curl -sL https://deb.nodesource.com/setup_18.x | bash -
  apt install -y nodejs
fi

# Verificar si npm está instalado
if ! command -v npm &> /dev/null; then
  curl -L https://www.npmjs.com/install.sh | sh
fi

# Verificar si SDKMAN está instalado
if [ ! -d "/root/.sdkman" ]; then
  curl -s "https://get.sdkman.io" | bash
  source "/root/.sdkman/bin/sdkman-init.sh"
fi

# Solicitar el nombre del proyecto de Angular
read -p "Ingrese el nombre del proyecto de Angular: " angular_project

# Crear la aplicación de Angular
npm install -g @angular/cli

# Verificar si el directorio Angular ya existe
if ! check_directory "Angular"; then
  mkdir Angular
fi

cd Angular

# Verificar si el directorio del proyecto Angular ya existe
if ! check_directory "$angular_project"; then
  ng new $angular_project
fi

cd ..


# Crear la aplicación de Spring Boot con Spring Boot CLI

# Verificar si el directorio SpringBoot ya existe
if ! check_directory "SpringBoot"; then
  mkdir SpringBoot
fi
cd SpringBoot
read -p "Ingrese el nombre del proyecto de Spring Boot: " spring_project
# Verificar si el directorio del proyecto Spring Boot ya existe
if ! check_directory "$spring_project"; then
  spring init --build=maven --java=17 --dependencies=web,devtools,data-jpa,actuator,mariadb,lombok --version=2.3.2.RELEASE --name=$spring_project $spring_project
fi

cd ..

# Mensaje final
cd Angular
cd $angular_project
ng server
echo "El servidor de desarrollo se ha configurado correctamente. La aplicación de Angular se está ejecutando en http://localhost:4200."

